
services:
  jugamos:
    image: ghcr.io/vincent/jugamos:main
    restart: unless-stopped
    volumes:
      - jugamos_data:/srv/jugamos/data
    ports:
      - 8090:8090

volumes:
  jugamos_data: # for persistent database
