volumes:
  chorezilla_data: # for persistent database

services:
  chorezilla:
    image: ghcr.io/vincent/chorezilla:main
    restart: unless-stopped
    environment:
      - CHOREZILLA_VAPID_PUBLIC_KEY=           # push notifications public key
      - CHOREZILLA_VAPID_PRIVATE_KEY=          # push notifications private key
      - CHOREZILLA_ADMIN_EMAIL=                # superadmin account email (optional)
      - CHOREZILLA_ADMIN_PASSWORD=             # superadmin account password (optional)
    volumes:
      - chorezilla_data:/srv/chorezilla/data
    ports:
      - 8090:8090
