export const icons = {
  'arm-dumbbell': 'arm-dumbbell-svgrepo-com.svg',
  'bathtub': 'bathtub-svgrepo-com.svg',
  'bed-2': 'bed-2-svgrepo-com.svg',
  'bicycle-3': 'bicycle-3-svgrepo-com.svg',
  'book-shelf': 'book-shelf-svgrepo-com.svg',
  'bottle-wine': 'bottle-wine-svgrepo-com.svg',
  'broom': 'broom-svgrepo-com.svg',
  'car-washing': 'car-washing-svgrepo-com.svg',
  'dining-room': 'dining-room-svgrepo-com.svg',
  'gamepad': 'gamepad-svgrepo-com.svg',
  'glass-drinks': 'glass-drinks-svgrepo-com.svg',
  'hair-washing-sink': 'hair-washing-sink-svgrepo-com.svg',
  'kitchen-cabinets': 'kitchen-cabinets-svgrepo-com.svg',
  'leisure': 'leisure-svgrepo-com.svg',
  'ping-pong': 'ping-pong-svgrepo-com.svg',
  'shower-2': 'shower-2-svgrepo-com.svg',
  'sleeping-in-bed': 'sleeping-in-bed-svgrepo-com.svg',
  'sofa': 'sofa-svgrepo-com.svg',
  'soup-plate': 'soup-plate-svgrepo-com.svg',
  'stove-cooking-pot': 'stove-cooking-pot-svgrepo-com.svg',
  'summer': 'summer-svgrepo-com.svg',
  'toilet-bowl': 'toilet-bowl-svgrepo-com.svg',
  'washing-machine': 'washing-machine-svgrepo-com.svg',
  'wing-chair': 'wing-chair-svgrepo-com.svg',
}